services:
  - type: web
    name: plant-app-backend
    runtime: node
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
    disks:
      - name: uploads
        mountPath: /app/uploads
        sizeGB: 1
